<template>
    <div class="users">
        <h1 class="md-display-1">Users</h1>
    </div>
</template>

<script>
export default {
    name: 'user-list',
    data() {
        return {

        };
    }
}
</script>

<style scoped>
    .users {
        background-color: #2962ff;
        height:100%;
        width:100%;
        border-radius: 0rem 0rem 1rem 1rem;
        overflow-y: scroll;
    }
</style>
